project_id = "hqhuzvinyhdheczbtseo"

[functions.auth]
verify_jwt = false

[functions.courses]
verify_jwt = false

[functions.services]
verify_jwt = false

[functions.appointments]
verify_jwt = false

[functions.orders]
verify_jwt = false

[functions.admin]
verify_jwt = false