// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hqhuzvinyhdheczbtseo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhxaHV6dmlueWhkaGVjemJ0c2VvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc0MjY5MTksImV4cCI6MjA3MzAwMjkxOX0.p6SMLfSkkxNRR7abu8judW8x6gli0KbdFOL-Hz69OHI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});